const SOCKET_ACTIONS = {
    TX_USERNAME: "TX_USERNAME",
    CREATE_ROOM: "CREATE_ROOM",
    JOIN_ROOM: "JOIN_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
    ATK_SUBMIT: "ATK_SUBMIT",
    VICTORY_CONTINUE: "VICTORY_CONTINUE"
};

module.exports = SOCKET_ACTIONS;